import { NextRequest, NextResponse } from "next/server"
import { createClient } from "@/lib/supabase/server"
import fs from "fs"
import path from "path"
import { randomUUID } from "crypto"

type RoomSpec = {
  name: string
  x: number
  y: number
  width: number
  height: number
}

type LayoutSpec = {
  title: string
  width: number
  height: number
  unit: string
  rooms: RoomSpec[]
}

export const runtime = "nodejs"

function clamp(value: number, min: number, max: number) {
  return Math.min(max, Math.max(min, value))
}

function escapeXml(input: string) {
  return input
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;")
}

function extractJsonObject(text: string) {
  const trimmed = text.trim()
  if (trimmed.startsWith("{")) return trimmed

  const first = trimmed.indexOf("{")
  const last = trimmed.lastIndexOf("}")
  if (first === -1 || last === -1 || last <= first) {
    throw new Error("Model did not return a JSON object")
  }
  return trimmed.slice(first, last + 1)
}

function normalizeLayout(raw: any, projectData: any): LayoutSpec {
  if (!raw || typeof raw !== "object") {
    throw new Error("Invalid layout object from model")
  }

  const width = clamp(Number(raw.width), 500, 760)
  const height = clamp(Number(raw.height), 500, 760)
  const unit = typeof raw.unit === "string" ? raw.unit : (projectData?.landUnit || "ft")
  const title = typeof raw.title === "string" && raw.title.trim().length > 0
    ? raw.title.trim()
    : `${projectData?.preferences?.style || "Custom"} Floor Plan`

  if (!Number.isFinite(width) || !Number.isFinite(height) || width <= 0 || height <= 0) {
    throw new Error("Model returned invalid layout dimensions")
  }

  if (!Array.isArray(raw.rooms) || raw.rooms.length === 0) {
    throw new Error("Model did not return rooms")
  }

  const rooms: RoomSpec[] = raw.rooms
    .map((room: any, i: number) => ({
      name: typeof room?.name === "string" && room.name.trim() ? room.name.trim() : `Room ${i + 1}`,
      x: Number(room?.x),
      y: Number(room?.y),
      width: Number(room?.width),
      height: Number(room?.height),
    }))
    .filter((r: RoomSpec) => Number.isFinite(r.x) && Number.isFinite(r.y) && Number.isFinite(r.width) && Number.isFinite(r.height))
    .map((r: RoomSpec) => ({
      ...r,
      x: clamp(r.x, 0, width - 1),
      y: clamp(r.y, 0, height - 1),
      width: clamp(r.width, 20, width),
      height: clamp(r.height, 20, height),
    }))
    .slice(0, 16)

  if (rooms.length === 0) {
    throw new Error("No valid rooms in model response")
  }

  return { title, width, height, unit, rooms }
}

function layoutToSvg(layout: LayoutSpec) {
  const palette = [
    "#B3E5FC",
    "#C8E6C9",
    "#FFF9C4",
    "#FFCCBC",
    "#D1C4E9",
    "#F8BBD0",
    "#CFD8DC",
  ]

  const roomsSvg = layout.rooms
    .map((room, i) => {
      const color = palette[i % palette.length]
      const cx = room.x + room.width / 2
      const cy = room.y + room.height / 2
      return `
        <rect x="${room.x}" y="${room.y}" width="${room.width}" height="${room.height}" fill="${color}" stroke="#1f2937" stroke-width="2" rx="4" ry="4" />
        <text x="${cx}" y="${cy}" font-family="Arial" font-size="14" text-anchor="middle" dominant-baseline="middle" fill="#111827">${escapeXml(room.name)}</text>
      `
    })
    .join("\n")

  return `
<svg width="900" height="700" xmlns="http://www.w3.org/2000/svg">
  <rect width="900" height="700" fill="#f8fafc" />
  <text x="450" y="36" font-family="Arial" font-size="22" font-weight="bold" text-anchor="middle" fill="#0f172a">${escapeXml(layout.title)}</text>

  <g transform="translate(80,80)">
    <rect x="0" y="0" width="${layout.width}" height="${layout.height}" fill="#ffffff" stroke="#111827" stroke-width="5" />
    ${roomsSvg}
  </g>

  <text x="80" y="670" font-family="Arial" font-size="12" fill="#334155">Generated by NVIDIA model</text>
  <text x="820" y="670" font-family="Arial" font-size="12" text-anchor="end" fill="#334155">Unit: ${layout.unit}</text>
</svg>
  `.trim()
}

async function generateLayoutWithNvidia(projectData: any): Promise<LayoutSpec> {
  const apiKey = process.env.NVIDIA_API_KEY
  if (!apiKey) {
    throw new Error("NVIDIA_API_KEY is missing")
  }

  const baseUrl = (process.env.NVIDIA_BASE_URL || "https://integrate.api.nvidia.com/v1").replace(/\/$/, "")
  const model = process.env.NVIDIA_MODEL || "meta/llama-3.1-70b-instruct"

  const bedrooms = projectData?.preferences?.rooms?.bedrooms ?? 2
  const bathrooms = projectData?.preferences?.rooms?.bathrooms ?? 2
  const style = projectData?.preferences?.style ?? "Modern"
  const stories = projectData?.preferences?.stories ?? 1
  const length = Number(projectData?.landDimensions?.length || 40)
  const width = Number(projectData?.landDimensions?.width || 30)
  const unit = projectData?.landUnit || "ft"

  const prompt = `You are an architect. Create a 2D floor plan layout as strict JSON only.

Requirements:
- Style: ${style}
- Stories: ${stories}
- Bedrooms: ${bedrooms}
- Bathrooms: ${bathrooms}
- Land: ${length} x ${width} ${unit}

Return exactly this JSON shape:
{
  "title": "string",
  "width": number,
  "height": number,
  "unit": "${unit}",
  "rooms": [
    { "name": "string", "x": number, "y": number, "width": number, "height": number }
  ]
}

Rules:
- width and height should be between 500 and 760
- Include at least: Living Room, Kitchen, Dining, ${bedrooms} bedrooms total, ${bathrooms} bathrooms total
- Ensure no room has zero/negative size
- Output JSON only, no markdown, no explanation.`

  const controller = new AbortController()
  const timeout = setTimeout(() => controller.abort(), 30_000)
  const response = await fetch(`${baseUrl}/chat/completions`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model,
      temperature: 0.2,
      messages: [
        { role: "system", content: "Return strict valid JSON only." },
        { role: "user", content: prompt },
      ],
    }),
    signal: controller.signal,
  }).finally(() => clearTimeout(timeout))

  const raw = await response.json().catch(() => null)
  if (!response.ok) {
    throw new Error(raw?.error?.message || "NVIDIA API request failed")
  }

  const rawContent = raw?.choices?.[0]?.message?.content
  const content =
    typeof rawContent === "string"
      ? rawContent
      : Array.isArray(rawContent)
      ? rawContent
          .map((part: any) => (typeof part?.text === "string" ? part.text : ""))
          .join("")
      : ""
  if (!content.trim()) {
    throw new Error("NVIDIA response missing content")
  }

  const jsonText = extractJsonObject(content)
  const parsed = JSON.parse(jsonText)
  return normalizeLayout(parsed, projectData)
}

export async function POST(req: NextRequest) {
  try {
    const supabase = await createClient()
    const {
      data: { user },
    } = await supabase.auth.getUser()

    if (!user?.id) {
      return NextResponse.json({ error: "Unauthorized. Please sign in to generate a floor plan." }, { status: 401 })
    }

    const projectData = await req.json().catch(() => null)
    if (!projectData) {
      return NextResponse.json({ error: "Missing project data" }, { status: 400 })
    }

    const layout = await generateLayoutWithNvidia(projectData)
    const svg = layoutToSvg(layout)

    const id = randomUUID()
    const dir = path.join(process.cwd(), "public", "uploads", "floor-plans", "generated")
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true })
    const fileName = `floor-plan-ai-${id}.svg`
    fs.writeFileSync(path.join(dir, fileName), svg, "utf8")

    const floorPlan = {
      projectId: projectData.id || "temp-project",
      userId: user.id,
      imageUrl: `/uploads/floor-plans/generated/${fileName}`,
      aiPrompt: JSON.stringify(projectData),
      description: `AI-generated ${projectData?.preferences?.style || "custom"} layout via NVIDIA model.`,
      generatedBy: "nvidia",
      dimensions: {
        width: Number(projectData?.landDimensions?.width) || 0,
        length: Number(projectData?.landDimensions?.length) || 0,
        unit: projectData?.landUnit || "sq ft",
      },
      rooms: {
        bedrooms: Number(projectData?.preferences?.rooms?.bedrooms) || 2,
        bathrooms: Number(projectData?.preferences?.rooms?.bathrooms) || 2,
      },
      style: projectData?.preferences?.style || "Modern",
      stories: Number(projectData?.preferences?.stories) || 1,
      createdAt: new Date(),
    }

    return NextResponse.json({ success: true, floorPlan }, { status: 201 })
  } catch (error: any) {
    console.error("Error generating real-time floor plan:", error)
    return NextResponse.json(
      {
        success: false,
        error: error?.message || "Failed to generate floor plan",
      },
      { status: 500 }
    )
  }
}
